### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [playingoDEERUX/GrowtopiaInternal#3]
Bro I get an error building the file. my discord name is : Cerberus of King#6306

NOTE: detours.h No Such or Directory.

![Screenshot_20200625-130518_Microsoft Remote Desktop](https://user-images.githubusercontent.com/67415855/85699913-92358080-b6e4-11ea-9146-362e183184c1.jpg)

**Comment by qatroxx** [comment]
ctrl+a+del

**Comment by playingoDEERUX** [comment]
Please make sure to set the include libraries in Visual Studio so that detours can be found.
