### ISSUE TITLE
CTD after injection

### ISSUE THREAD

**Issue by anzenchitai** [playingoDEERUX/GrowtopiaInternal#5]
I am running Growtopia 3.38 Beta PC version but it crashes after injection. I also tried manual mapping but no luck. Am I doing something wrong?

**Comment by playingoDEERUX** [comment]
Use 3.37, it has version spoofer to version 4.20 (fake version) and I am too lazy to update the internal itself to make it work with 3.38, it is inefficient to update the internal for each new growtopia version, its instead better to just edit the version string and keep using 3.37.
